name: CI
 
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  m1:
    runs-on: ubuntu-latest
    environment:
      name: mensagem 1
      url: https://voidgodhand.github.io/joaogabrielalegria-cscw-pipeline-cicd/index.html
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: mensagem 1
        run: echo Present day... haha

  m2:
    runs-on: ubuntu-latest
    environment:
      name: mensagem 2
      url: https://voidgodhand.github.io/joaogabrielalegria-cscw-pipeline-cicd/index.html
    needs: m1
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: mensagem 2
        run: echo PRESENT TIME

  m3:
    runs-on: ubuntu-latest
    environment:
      name: mensagem 3
      url: https://voidgodhand.github.io/joaogabrielalegria-cscw-pipeline-cicd/index.html
    needs: m2
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: mensagem 3
        run: echo HAHAHAHAHAHAHA


