name: CI
 
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  mensagem_1:
    runs-on: ubuntu-latest
    environment:
      name: m1
      url: https://voidgodhand.github.io/joaogabrielalegria-cscw-pipeline-cicd/index.html
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: mensagem 1
        run: echo Present day... haha

  mensagem_2:
    runs-on: ubuntu-latest
    environment:
      name: m2
      url: https://voidgodhand.github.io/joaogabrielalegria-cscw-pipeline-cicd/index.html
    needs: mensagem_1
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: mensagem 2
        run: echo PRESENT TIME

  mensagem_3:
    runs-on: ubuntu-latest
    environment:
      name: m3
      url: https://voidgodhand.github.io/joaogabrielalegria-cscw-pipeline-cicd/index.html
    needs: mensagem_2
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: mensagem 3
        run: echo HAHAHAHAHAHAHA


